# Generated by Django 5.2.5 on 2025-09-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
