# Generated by Django 5.2.5 on 2025-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_complaint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
