# Generated by Django 5.2.5 on 2025-10-02 10:03

import Home.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_custom_complaint_id_start_100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=Home.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=Home.encryption.EncryptedCharField(max_length=500),
        ),
    ]
