# Generated by Django 5.2.5 on 2025-09-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_complaint_division'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
