# Generated by Django 5.2.5 on 2025-10-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_add_encryption_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Actions taken by admin to resolve the complaint'),
        ),
    ]
