# Generated by Django 5.2.5 on 2025-10-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_complaint_action_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='action_image',
            field=models.FileField(blank=True, help_text='Image proof of action taken', null=True, upload_to='action_images/'),
        ),
    ]
